### ISSUE TITLE
Bug：name 'conv_blocks_size_5' is not defined

### ISSUE THREAD

**Issue by ulen2000** [peylnog/CRDNet#1]
Your paper ‘Cumulative Rain Density Sensing Network for Single Image Derain ’ is in line with my research direction. There are many places in the paper  gave me great reference value. However, when I tested your code, I found some errors in your code。
Hope you can check the code and look forward to your reply

<img width="730" alt="微信图片_20200407192445" src="https://user-images.githubusercontent.com/58459187/78759685-96d67c80-79b2-11ea-84af-040018204523.png">

**Comment by peylnog** [comment]
I've changed the code.
