### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by ulen2000** [peylnog/CRDNet#3]
When i run your code,it shows ValueError,as show in the follow image 
![QQ截图20200408190426](https://user-images.githubusercontent.com/58459187/78777269-d2ca0b80-79cb-11ea-88f7-cfe7699d1ce6.png)

Besides ,could you show me your  data root and path code in your DefaultConfig() as well as some code in your test(). The three parts as my follow images.
![QQ截图20200408190332](https://user-images.githubusercontent.com/58459187/78777714-9e0a8400-79cc-11ea-8b4f-8d510d3ea3d7.png)
![QQ截图20200408190352](https://user-images.githubusercontent.com/58459187/78777721-a236a180-79cc-11ea-824d-4494cd87bbe8.png)
![QQ截图20200408190409](https://user-images.githubusercontent.com/58459187/78777722-a2cf3800-79cc-11ea-81ea-7c687a8b5587.png)

**Comment by peylnog** [comment]
There is no error in my model , please make sure your data path and pytorch_datasets(It depends on your job) is right. For your question , test_data_root is empty.
